---
title: "Linda Karani CV"
author: Linda Karani
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
#uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---


Aside
================================================================================


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> karanilinda@gmail.com
- <i class="fa fa-github"></i> [github.com/KaraniLinda](https://github.com/KaraniLinda)
- <i class="fa fa-linkedin"></i> [Linkedin](https://www.linkedin.com/in/linda-karani-369b3112b/)
- <i class="fa fa-phone"></i> +254 708054713



Data tech stack {#skills}
--------------------------------------------------------------------------------

**Database/Server** : MySQL, PostgreSQL

**Programming languages** : Python, R programming

**Frameworks/libraries** : NumPy, Pandas, matplotlib, Scikit-learn, ggplot, tidyverse, dplyr, leaflet, caret

**Data visualization/Reporting** : R Markdown, Quarto, Power BI, Tableau , Google Data Studio, Excel

**Geospatial packages**: Uber-H3(Hexagon), ARCGIS, R(raster,tmap), Python (geopandas, rasterio, xarray)

**Cloud computing** : Google cloud platform

Git and Version Control

Languages {#languages}
--------------------------------------------------------------------------------

English : Native

French : Limited working proficiency



Main
================================================================================

LINDA KARANI {#title}
--------------------------------------------------------------------------------

### Data Scientist

I am a seasoned data scientist with around 5 years of experience specializing in developing data-intensive tools, comprehensive data processing, intricate data analysis, and predictive modeling. I excel in transforming raw data into actionable insights via interactive and analytical dashboards. My expertise extends to both supervised and unsupervised machine learning, advanced statistical analysis, and geospatial data analysis. I am also proficient in SQL and comfortable with data modeling. I am highly adaptable and thrive in navigating ambiguous and unstructured environments, where I can build innovative solutions from scratch.

My strength lies in consistently driving value for stakeholders and across the organization through through effective storytelling, problem solving and deriving meaningful and actionable insights from data to inform decision making. I am driven by the pursuit of continuous learning, contribution to societal good and actively seek out new challenges to further enhance my expertise.

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Strathmore University

Masters of Science in Data Science and Analytics

Nairobi, Kenya

2021 - 2024

Relevant units: Advanced machine learning concepts, Advanced statistical 
analysis, Data visualization and communication, Database management

### ETH Zurich

Dissertation: Importance of reproducibility in advancing Sustainable Development Goal(SDG) 6 in R : A comparison of statistical models

Zurich, Switzerland

2022

### Strathmore University

Bachelor of Business Science in Financial Economics

Nairobi, Kenya

2014 - 2018

Certifications {data-icon=certificate data-concise=true}
--------------------------------------------------------------------------------

### IBM

Data Engineering & Data science 

Remote

2024

Relevant units: Data Managemant, ETL, Apache, Databases, Data Warehousing,
Distributed computing systems, SQL. Generative AI

### Esri

Spatial data science

Remote

2024


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Data scientist

World data lab

Nairobi, Kenya

November, 2022 - Date

- Led the comprehensive data collection, analysis, and forecasting for multiple projects including the in-depth analysis of youth labor force survey data in collaboration with the Mastercard Foundation. Executed the project for Kenya, Rwanda, and Ghana, leading to the establishment of a youth unemployment clock providing real-time insights on jobs. Utilized advanced statistical modelling techniques such as linear regression and time series models to forecast future labour market trends
- Utilized predictive modeling techniques to analyze satellite data such as land cover and nightlights data and demographic information, creating a detailed map of aggregate spending for European countries at the grid (100m*100m) and hexagon level (Uber H3 - Res 9), enabling our client to identify optimal locations for retail chain expansion.
- Applied and deployed advanced machine learning algorithms such as Random Forest and regularized regression models at the lowest census unit for European countries, leveraging geospatial covariates to effectively disaggregate spending at the grid level with a 86% accuracy. 
- Organized and executed student hackathons with participation from over 100 students and in collaboration with the top 3 universities in Kenya, resulting in the development of innovative solutions for real-world problems and fostering collaboration within the academic community.
- Conducting rigorous data quality assurance checks, ensuring the continuous enhancement of models with the latest and highest-quality data.
- Demonstrated expertise in the in-depth analysis of household and census survey data.
- Delivered high-impact, actionable insights to clients, focusing on providing data-driven solutions that directly informed strategic decision-making and drove meaningful results.


### Senior associate- Data analysis and business modelling

Sanergy

Nairobi, Kenya


April, 2021 - November, 2022


- Was part of a team that led data management and analysis for a multinational
corporation to identify areas in the citywith the greatest potential for 
introduction of non-sewered sanitation products to allow for future upscale 
- Developed several robust quantitative and qualitative data collection tools
for citywide inclusive sanitation planning to determine market share and 
predict an appropriate mix of sanitation products based on key indicators
and metrics.
- Analyzed data collected by the Cost and Climate in Urban Sanitation (CACTUS)
project led by the University of Leeds and supported by the Bill and Melinda 
Gates Foundation and used the findings to create a set of improved data 
collection tools and manuals to facilitate widespread contribution to a
database of benchmark cost estimates to inform sanitation investment decisions.
- Effectively communicating analysis and project results to senior leadership
and external stakeholders
- Completion of diverse advisory projects with a high standard of quality and
production of comprehensive analytical reports
- Conducted data analysis for a UNICEF implemented project to inform progress
towards safely managed sanitation
- Proactive stakeholder management and advisory services


### Finance/Data analyst

Sanergy.

Nairobi, Kenya

September, 2019 - March, 2021


- Identified key organizational metrics, cleaned and analyzed data from all 
departments and presented results on Tableau improving accuracy of results 
by 35%. 
- Aggregated data across all departments that was previously in multiple
different sources to create an interactive organization wide dashboard based on
key KPIs that led to increased efficiency in operations and improved decision
making and that resulted in a 30% reduction in redundancy.
- Using data analytics to identify business needs and requirements and deliver
data-driven recommendations and reports to executives and stakeholders. 
- Supported teams to understand, monitor and control key business metrics to 
achieve success and base decisions on data.
- Prepared financial statements and other financial reports
and reported performance to senior management and the
finance board



References
--------------------------------------------------------------------------------


<div style="text-align: left; margin-left: 60px;">

References available upon request
</div>


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------


This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.


